// Material Icons 注册表
// 将字符串名称映射到 Flutter IconData，供 button.icon / input.prefixIcon 等使用
import 'package:flutter/material.dart';

class IconRegistry {
  static final Map<String, IconData> _icons = {
    // 导航
    'home': Icons.home,
    'insights': Icons.insights,
    'back': Icons.arrow_back,
    'forward': Icons.arrow_forward,
    'menu': Icons.menu,
    'close': Icons.close,
    'more': Icons.more_vert,
    'more_horiz': Icons.more_horiz,

    // 操作
    'add': Icons.add,
    'remove': Icons.remove,
    'delete': Icons.delete,
    'edit': Icons.edit,
    'save': Icons.save,
    'copy': Icons.copy,
    'paste': Icons.paste,
    'share': Icons.share,
    'send': Icons.send,
    'upload': Icons.upload,
    'download': Icons.download,
    'refresh': Icons.refresh,
    'sync': Icons.sync,
    'undo': Icons.undo,
    'redo': Icons.redo,

    // 文件
    'folder': Icons.folder,
    'file': Icons.insert_drive_file,
    'attachment': Icons.attach_file,
    'image': Icons.image,
    'photo': Icons.photo,
    'camera': Icons.camera_alt,
    'video': Icons.videocam,
    'audio': Icons.audiotrack,

    // 通信
    'email': Icons.email,
    'phone': Icons.phone,
    'chat': Icons.chat,
    'message': Icons.message,
    'notification': Icons.notifications,

    // 用户
    'person': Icons.person,
    'people': Icons.people,
    'account': Icons.account_circle,
    'login': Icons.login,
    'logout': Icons.logout,

    // 状态
    'check': Icons.check,
    'check_circle': Icons.check_circle,
    'error': Icons.error,
    'warning': Icons.warning,
    'warning_amber': Icons.warning_amber,
    'info': Icons.info,
    'help': Icons.help,
    'block': Icons.block,

    // 内容
    'search': Icons.search,
    'filter': Icons.filter_list,
    'sort': Icons.sort,
    'star': Icons.star,
    'star_outline': Icons.star_outline,
    'favorite': Icons.favorite,
    'favorite_outline': Icons.favorite_border,
    'bookmark': Icons.bookmark,
    'bookmark_outline': Icons.bookmark_border,
    'tag': Icons.label,
    'link': Icons.link,
    'code': Icons.code,

    // UI
    'settings': Icons.settings,
    'tune': Icons.tune,
    'palette': Icons.palette,
    'dark_mode': Icons.dark_mode,
    'light_mode': Icons.light_mode,
    'visibility': Icons.visibility,
    'visibility_off': Icons.visibility_off,
    'lock': Icons.lock,
    'unlock': Icons.lock_open,
    'key': Icons.vpn_key,

    // 方向
    'up': Icons.arrow_upward,
    'down': Icons.arrow_downward,
    'left': Icons.arrow_back,
    'right': Icons.arrow_forward,
    'expand': Icons.expand_more,
    'collapse': Icons.expand_less,
    'fullscreen': Icons.fullscreen,

    // 游戏 / 历史
    'history': Icons.history,
    'replay': Icons.replay,
    'restart': Icons.restart_alt,
    'pause': Icons.pause,
    'play': Icons.play_arrow,
    'stop': Icons.stop,
    'trophy': Icons.emoji_events,
    'leaderboard': Icons.leaderboard,
    'timeline': Icons.timeline,

    // 其他
    'ac_unit': Icons.ac_unit,
    'air': Icons.air,
    'bathroom': Icons.bathroom,
    'bathtub': Icons.bathtub,
    'bed': Icons.bed,
    'blinds': Icons.blinds,
    'bolt': Icons.bolt,
    'calendar': Icons.calendar_today,
    'chair': Icons.chair,
    'chevron_right': Icons.chevron_right,
    'clock': Icons.access_time,
    'cleaning_services': Icons.cleaning_services,
    'cooking': Icons.restaurant,
    'curtains': Icons.curtains,
    'devices': Icons.devices,
    'door_front': Icons.door_front_door,
    'electric_bolt': Icons.electric_bolt,
    'garage': Icons.garage,
    'health_and_safety': Icons.health_and_safety,
    'inventory_2': Icons.inventory_2,
    'king_bed': Icons.king_bed,
    'kitchen': Icons.kitchen,
    'lightbulb': Icons.lightbulb,
    'local_laundry_service': Icons.local_laundry_service,
    'local_pharmacy': Icons.local_pharmacy,
    'location': Icons.location_on,
    'map': Icons.map,
    'medication': Icons.medication,
    'menu_book': Icons.menu_book,
    'monitor_heart': Icons.monitor_heart,
    'notes': Icons.notes,
    'payments': Icons.payments,
    'power': Icons.power_settings_new,
    'power_settings_new': Icons.power_settings_new,
    'globe': Icons.language,
    'restaurant': Icons.restaurant,
    'room_preferences': Icons.room_preferences,
    'router': Icons.router,
    'schedule': Icons.schedule,
    'security': Icons.security,
    'sensors': Icons.sensors,
    'single_bed': Icons.single_bed,
    'spa': Icons.spa,
    'thermostat': Icons.thermostat,
    'thermostat_auto': Icons.thermostat_auto,
    'theaters': Icons.theaters,
    'today': Icons.today,
    'tv': Icons.tv,
    'water_drop': Icons.water_drop,
    'wb_sunny': Icons.wb_sunny,
    'weekend': Icons.weekend,
    'wifi': Icons.wifi,
    'bluetooth': Icons.bluetooth,
    'print': Icons.print,
    'qr_code': Icons.qr_code,
    'fingerprint': Icons.fingerprint,
    'emoji': Icons.emoji_emotions,
    'list': Icons.list,
    'grid': Icons.grid_view,
    'dashboard': Icons.dashboard,
    'analytics': Icons.analytics,
    'receipt': Icons.receipt,
    'shopping_cart': Icons.shopping_cart,
    'payment': Icons.payment,
  };

  static IconData? get(String name) => _icons[name];

  /// 列出所有可用图标名（调试用）
  static List<String> get allNames => _icons.keys.toList()..sort();
}
